"""
===================================================================================
HYBRID MACHINE LEARNING FRAMEWORK FOR DEPRESSION DETECTION IN CANCER PATIENTS
===================================================================================
Version: 2.0
Fixes over v1
-------------
  ✗ FCRI item-15 mapping wrong (a few times a month→2, should be→1)
  ✗ FCRI item-17 mapping wrong ('since my diagnosis' not in data; should be 'Several years')
  ✗ XGBoost: use_label_encoder=False deprecated → removed
  ✗ XGBoost multiclass: multi:softmax → multi:softprob (needed for soft VotingClassifier)
  ✗ XGBoost eval_metric for multiclass: 'logloss' → 'mlogloss'
  ✗ StandardScaler fitted twice (binary then multiclass), second call overwrites first
  ✗ Two independent train/test splits — now one shared split for both tasks
  ✗ ModelEvaluator received wrong scaler for binary evaluation
  ✗ No ROC-AUC metric
  ✗ No class-weight balancing (LR and RF)
  ✗ feature_cols not persisted — predictor couldn't reconstruct the feature vector
  ✗ v2 demographic columns (Cancer Stage, Education, Marital, Employment, Site, Prior Psych)
    not included in feature engineering
"""

import warnings
warnings.filterwarnings('ignore')

import json
import os
import numpy as np
import pandas as pd
import joblib
import re

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, classification_report,
                             confusion_matrix, ConfusionMatrixDisplay)
from sklearn.utils.class_weight import compute_class_weight
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)


# =============================================================================
# SECTION 1: DATA PREPROCESSING & CLEANING LAYER
# =============================================================================

class ClinicalDataPreprocessor:
    """Comprehensive data preprocessing for clinical psychometric data.

    Supports two column-naming conventions:
      • Legacy CSV   : BDI items named '1.' … '21.', FCRI items start with 'N. '
      • Clean/v2     : BDI items named 'BDI_1' … 'BDI_21', FCRI 'FCRI_1' … 'FCRI_42'
    Supports two response formats:
      • Text string  : 'I feel sad', 'Somewhat', 'A few times a week', …
      • Digit-prefix : '1 - I feel sad', '2 - Somewhat', …  (v2 Google Forms output)
      • Plain integer: 0, 1, 2, 3, 4  (generated by mock data or pre-processed)
    """

    FCRI_SUBSCALES = {
        'triggers':               list(range(1, 9)),
        'severity':               list(range(9, 18)),   # item 13 reversed before summing
        'psychological_distress': list(range(18, 22)),
        'functioning_impairments':list(range(22, 28)),
        'insight':                list(range(28, 31)),
        'reassurance':            list(range(31, 34)),
        'coping_strategies':      list(range(34, 43)),
    }

    # ── Fixed FCRI text → integer mappings ───────────────────────────────────
    # Key bugs fixed:
    #   item 15: 'a few times a month'→1 (was 2), 'a few times a week'→2 (was 3),
    #            'several times a day'→4 (was missing), removed 'a few times a year'/'at least once a day'
    #   item 17: 'several years'→4 (was 'since my diagnosis' which doesn't exist in data)
    FCRI_SCORE_MAP = {
        # Frequency scale (Triggers, Reassurance, Coping, Reassurance Effectiveness)
        'never': 0, 'rarely': 1, 'sometimes': 2, 'most of the time': 3, 'all the time': 4,
        # Intensity scale (Severity 9-13, Distress, Functioning, Insight)
        'not at all': 0, 'a little': 1, 'somewhat': 2, 'a lot': 3, 'a great deal': 4,
        # Item 14 — risk perception
        'not at all at risk': 0, 'a little at risk': 1, 'somewhat at risk': 2,
        'a lot at risk': 3, 'a great deal at risk': 4,
        # Item 15 — frequency (FIXED: correct 0-4 order)
        'a few times a month': 1, 'a few times a week': 2,
        'a few times a day': 3, 'several times a day': 4,
        # Item 16 — time per day
        "i don't think about it": 0, 'a few seconds': 1, 'a few minutes': 2,
        'a few hours': 3, 'several hours': 4,
        # Item 17 — duration (FIXED: 'several years' not 'since my diagnosis')
        'a few weeks': 1, 'a few months': 2, 'a few years': 3, 'several years': 4,
    }

    def __init__(self):
        self.bdi_columns  = []
        self.fcri_columns = []
        self.demographic_columns = {}
        self.label_encoders = {}

    # ── Column identification ─────────────────────────────────────────────────

    def _identify_columns(self, df):
        cols = df.columns.tolist()

        # BDI: legacy '1.'…'21.' OR clean 'BDI_1'…'BDI_21'
        legacy_bdi = {f'{i}.' for i in range(1, 22)}
        clean_bdi  = {f'BDI_{i}' for i in range(1, 22)}
        self.bdi_columns = [c for c in cols
                            if c.strip() in legacy_bdi or c.strip() in clean_bdi]

        # FCRI: legacy 'N. <text>' OR clean 'FCRI_N'
        clean_fcri = {f'FCRI_{i}' for i in range(1, 43)}
        self.fcri_columns = []
        for c in cols:
            cs = c.strip()
            if cs in clean_fcri:
                self.fcri_columns.append(c)
                continue
            for n in range(1, 43):
                if cs.startswith(f'{n}. ') and len(cs) > len(f'{n}. ') + 3:
                    self.fcri_columns.append(c)
                    break

        # Demographic columns — updated for both legacy and v2 field names
        self.demographic_columns = {
            'gender':            self._find_col(cols, ['gender']),
            'age_group':         self._find_col(cols, ['age group', 'age_group']),
            'province':          self._find_col(cols, ['province', 'povince']),
            'cancer_type':       self._find_col(cols, ['cancer type', 'cancer_type']),
            'cancer_stage':      self._find_col(cols, ['cancer stage', 'cancer_stage']),        # v2
            'treatment_type':    self._find_col(cols, ['treatment type', 'current treatment']),
            'cancer_status':     self._find_col(cols, ['cancer status']),
            'collection_site':   self._find_col(cols, ['collection site', 'data collection']),  # v2
            'education_level':   self._find_col(cols, ['education level', 'education_level']),  # v2
            'marital_status':    self._find_col(cols, ['marital status', 'marital_status']),    # v2
            'employment_status': self._find_col(cols, ['employment status', 'employment_status']),# v2
            'prior_psych':       self._find_col(cols, ['prior psych', 'prior_psych']),          # v2
            'on_medication':     self._find_col(cols, ['medication for depression',
                                                        'on_psych_medication',
                                                        'taking any medication']),
            'diagnosis_duration':self._find_col(cols, ['duration since diagnosis',
                                                        'duration_since_diagnosis']),
        }

        n_found_demo = sum(1 for v in self.demographic_columns.values() if v is not None)
        print(f"  BDI columns  : {len(self.bdi_columns)}")
        print(f"  FCRI columns : {len(self.fcri_columns)}")
        print(f"  Demo columns : {n_found_demo}/{len(self.demographic_columns)} found")

    def _find_col(self, cols, terms):
        for c in cols:
            for t in terms:
                if t.lower() in c.lower().strip():
                    return c
        return None

    # ── Numeric conversion ────────────────────────────────────────────────────

    def _parse_bdi(self, val) -> float:
        """Convert any BDI response format to 0-3 integer."""
        if pd.isna(val):
            return np.nan
        s = str(val).strip().lower().rstrip('.')

        # Already numeric (mock data or pre-processed)
        try:
            v = float(s)
            if v in (0, 1, 2, 3):
                return int(v)
        except ValueError:
            pass

        # v2 digit-prefix format: '2 - I am sad all the time...'
        if re.match(r'^[0-3] - ', s):
            try:
                return int(s[0])
            except ValueError:
                pass

        # Keyword matching for legacy text format (ordered highest→lowest severity)
        keywords = {
            3: ['so sad and unhappy', 'future is hopeless', 'complete failure',
                'dissatisfied or bored', 'guilty all of the time', 'i am being punished',
                'hate myself', 'blame myself for everything', 'would kill myself if i had',
                "can't cry even though", 'irritated all the time', 'lost all of my interest',
                "can't make decisions at all", 'look ugly', "can't do any work",
                'several hours earlier', 'too tired to do anything', 'no appetite at all',
                'lost more than fifteen', 'so worried about my physical',
                'lost interest in sex completely'],
            2: ['sad all the time', 'nothing to look forward', 'lot of failures',
                "don't get real satisfaction", 'quite guilty most', 'expect to be punished',
                'disgusted with myself', 'blame myself all the time', 'would like to kill myself',
                'cry all the time', 'quite annoyed', 'lost most of my interest',
                'greater difficulty in making', 'permanent changes in my appearance',
                'push myself very hard', '1-2 hours earlier', 'tired from doing almost',
                'appetite is much worse', 'lost more than ten', 'very worried about physical',
                'almost no interest in sex'],
            1: ['i feel sad', 'feel discouraged', 'failed more than',
                "don't enjoy things", 'guilty a good part', 'may be punished',
                'disappointed in myself', 'critical of myself',
                'thoughts of killing myself, but', 'cry more now than',
                'slightly more irritated', 'less interested in other people',
                'put off making decisions', 'worried that i am looking',
                'extra effort to get started', "don't sleep as well",
                'get tired more easily', 'appetite is not as good', 'lost more than five',
                'worried about physical problems', 'less interested in sex than'],
        }
        for score in (3, 2, 1):
            if any(kw in s for kw in keywords[score]):
                return score
        return 0  # default to 0 if no keyword match

    def _parse_fcri(self, val) -> float:
        """Convert any FCRI response format to 0-4 integer."""
        if pd.isna(val):
            return np.nan
        s = str(val).strip()

        # Already numeric
        try:
            v = float(s)
            if 0 <= v <= 4:
                return int(v)
        except ValueError:
            pass

        # v2 digit-prefix: '0 - Not at all'
        if re.match(r'^[0-4] - ', s):
            try:
                return int(s[0])
            except ValueError:
                pass

        # Text lookup
        return self.FCRI_SCORE_MAP.get(s.lower(), np.nan)

    def _convert_to_numeric(self, df):
        df = df.copy()
        for col in self.bdi_columns:
            if col in df.columns:
                df[col] = df[col].apply(self._parse_bdi)
        for col in self.fcri_columns:
            if col in df.columns:
                df[col] = df[col].apply(self._parse_fcri)
        return df

    # ── FCRI item 13 reversal ─────────────────────────────────────────────────

    def _reverse_fcri_item_13(self, df):
        """Reverse-score FCRI item 13 (I believe I am cured). reversed = 4 − raw."""
        for col in self.fcri_columns:
            cs = col.strip()
            # Matches legacy '13. I believe...' or clean 'FCRI_13'
            if cs == 'FCRI_13' or cs.startswith('13. '):
                df = df.copy()
                df[col] = pd.to_numeric(df[col], errors='coerce')
                df[col] = 4 - df[col]
                print("  Reversed FCRI item 13")
                break
        return df

    # ── Quality filters ───────────────────────────────────────────────────────

    def _drop_mechanical(self, df):
        if not self.fcri_columns:
            return df
        mask = (df[self.fcri_columns] == 0).all(axis=1)
        n = mask.sum()
        if n:
            print(f"  Dropped {n} mechanical-response rows (all FCRI = 0)")
            df = df[~mask].reset_index(drop=True)
        return df

    def _drop_excessive_missing(self, df, threshold=0.5):
        q_cols  = self.bdi_columns + self.fcri_columns
        pct_nan = df[q_cols].isna().mean(axis=1)
        mask    = pct_nan > threshold
        n = mask.sum()
        if n:
            print(f"  Dropped {n} rows with >{threshold*100:.0f}% missing questionnaire items")
            df = df[~mask].reset_index(drop=True)
        return df

    # ── Subscale-mean imputation ──────────────────────────────────────────────

    def _get_subscale_cols(self, subscale_name):
        nums = self.FCRI_SUBSCALES[subscale_name]
        candidates_legacy = {f'{n}.' for n in nums} | {f'{n} ' for n in nums}
        candidates_clean  = {f'FCRI_{n}' for n in nums}
        result = []
        for col in self.fcri_columns:
            cs = col.strip()
            if cs in candidates_clean:
                result.append(col)
            else:
                for n in nums:
                    if cs.startswith(f'{n}. ') or cs.startswith(f'{n}.'):
                        result.append(col)
                        break
        return result

    def _impute_subscale_means(self, df):
        df = df.copy()
        for col in self.bdi_columns + self.fcri_columns:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        # BDI: impute with patient's own BDI mean
        if self.bdi_columns:
            bdi_means = df[self.bdi_columns].astype(float).mean(axis=1)
            for col in self.bdi_columns:
                mask = df[col].isna()
                if mask.any():
                    df.loc[mask, col] = bdi_means[mask].round()

        # FCRI: impute with patient's own subscale mean
        for sub in self.FCRI_SUBSCALES:
            sub_cols = [c for c in self._get_subscale_cols(sub) if c in df.columns]
            if not sub_cols:
                continue
            sub_means = df[sub_cols].astype(float).mean(axis=1)
            for col in sub_cols:
                mask = df[col].isna()
                if mask.any():
                    df.loc[mask, col] = sub_means[mask].round()
        return df

    # ── Categorical encoding ──────────────────────────────────────────────────

    def _encode_categoricals(self, df):
        df = df.copy()
        encoded = []
        for name, col in self.demographic_columns.items():
            if col is None or col not in df.columns:
                continue
            df[col] = df[col].fillna('Unknown').astype(str).str.strip()
            le = LabelEncoder()
            enc_col = f'{name}_encoded'
            df[enc_col] = le.fit_transform(df[col])
            self.label_encoders[name] = le
            encoded.append(enc_col)
        return df, encoded

    # ── Master pipeline ───────────────────────────────────────────────────────

    def fit_transform(self, df):
        print("=" * 60)
        print("DATA PREPROCESSING")
        print("=" * 60)
        df_out = df.copy()
        n_in   = len(df_out)
        print(f"  Input rows: {n_in:,}")

        self._identify_columns(df_out)

        # Drop PII
        for col in ['Name', 'Timestamp', 'Patient Code / ID', 'Patient_ID']:
            if col in df_out.columns:
                df_out = df_out.drop(columns=[col])

        df_out = self._convert_to_numeric(df_out)

        # Conversion quality check
        if self.bdi_columns:
            ok = df_out[self.bdi_columns].notna().mean().mean()
            print(f"  BDI conversion rate : {ok*100:.1f}%")
            if ok < 0.80:
                print("  WARNING: BDI conversion rate below 80% — check response text formats.")
        if self.fcri_columns:
            ok = df_out[self.fcri_columns].notna().mean().mean()
            print(f"  FCRI conversion rate: {ok*100:.1f}%")
            if ok < 0.80:
                print("  WARNING: FCRI conversion rate below 80% — check response text formats.")

        df_out = self._reverse_fcri_item_13(df_out)
        df_out = self._drop_mechanical(df_out)
        df_out = self._drop_excessive_missing(df_out)
        df_out = self._impute_subscale_means(df_out)
        df_out, enc_features = self._encode_categoricals(df_out)

        print(f"  Output rows : {len(df_out):,}  (dropped {n_in - len(df_out):,})")
        print("=" * 60)
        return df_out, enc_features


# =============================================================================
# SECTION 2: TARGET VARIABLE ENGINEERING
# =============================================================================

class TargetVariableEngineer:

    SEVERITY_BOUNDS = [
        ('Normal',                       0,  10),
        ('Mild mood disturbance',        11, 16),
        ('Borderline clinical depression',17, 20),
        ('Moderate depression',          21, 30),
        ('Severe depression',            31, 40),
        ('Extreme depression',           41, 63),
    ]
    SEVERITY_LABELS = [s[0] for s in SEVERITY_BOUNDS]

    def __init__(self, bdi_columns):
        self.bdi_columns = bdi_columns
        self.encoder = LabelEncoder()
        self.encoder.fit(self.SEVERITY_LABELS)

    def bdi_total(self, df):
        return df[self.bdi_columns].apply(pd.to_numeric, errors='coerce').sum(axis=1)

    def score_to_severity(self, score):
        if pd.isna(score):
            return 'Unknown'
        for label, lo, hi in self.SEVERITY_BOUNDS:
            if lo <= score <= hi:
                return label
        return 'Unknown'

    def create_targets(self, df):
        print("\n" + "=" * 60)
        print("TARGET VARIABLE ENGINEERING")
        print("=" * 60)
        df = df.copy()
        df['bdi_total']    = self.bdi_total(df)
        df['depression_severity']         = df['bdi_total'].apply(self.score_to_severity)
        df['depression_severity_encoded'] = self.encoder.transform(df['depression_severity'])
        df['has_depression']              = (df['bdi_total'] >= 11).astype(int)

        print(f"  BDI score  — mean {df['bdi_total'].mean():.1f}, "
              f"std {df['bdi_total'].std():.1f}, "
              f"range [{df['bdi_total'].min():.0f}, {df['bdi_total'].max():.0f}]")
        print(f"  Binary    : {df['has_depression'].value_counts().to_dict()}")
        print(f"  Multiclass: {df['depression_severity'].value_counts().to_dict()}")
        print("=" * 60)
        return df


# =============================================================================
# SECTION 3: MODEL TRAINING & ENSEMBLE
# =============================================================================

class DepressionClassificationPipeline:

    def __init__(self, random_state=42):
        self.random_state = random_state
        self.models = {}

    def _tune(self, estimator, param_grid, X_scaled, y, cv, name):
        print(f"\n  Tuning {name}…")
        gs = GridSearchCV(estimator, param_grid, cv=cv,
                          scoring='f1_weighted', n_jobs=-1, verbose=0)
        gs.fit(X_scaled, y)
        print(f"    Best params : {gs.best_params_}")
        print(f"    Best CV F1  : {gs.best_score_:.4f}")
        return gs.best_estimator_

    def train(self, X_train_scaled, y_train, task='binary'):
        """Train and tune LR, RF, XGBoost; build soft-vote ensemble."""
        print(f"\n{'='*60}")
        print(f"TRAINING {task.upper()} MODELS")
        print("=" * 60)

        cv           = StratifiedKFold(n_splits=5, shuffle=True,
                                       random_state=self.random_state)
        class_weight = 'balanced'   # handles class imbalance for LR and RF

        # ── Logistic Regression ───────────────────────────────────────────────
        lr = self._tune(
            LogisticRegression(random_state=self.random_state, max_iter=1000,
                               solver='lbfgs', class_weight=class_weight),
            {'C': [0.01, 0.1, 1, 10], 'penalty': ['l2']},
            X_train_scaled, y_train, cv, "Logistic Regression"
        )

        # ── Random Forest ─────────────────────────────────────────────────────
        rf = self._tune(
            RandomForestClassifier(random_state=self.random_state, n_jobs=-1,
                                   class_weight=class_weight),
            {'n_estimators': [100, 200], 'max_depth': [5, 10, None],
             'min_samples_split': [2, 5]},
            X_train_scaled, y_train, cv, "Random Forest"
        )

        # ── XGBoost (FIXED) ───────────────────────────────────────────────────
        # Binary  : binary:logistic / logloss
        # Multiclass: multi:softprob (returns proba — required for soft voting)
        #             eval_metric: mlogloss (not 'logloss' which is for binary only)
        # Removed deprecated: use_label_encoder=False
        if task == 'binary':
            xgb_kwargs = {'objective': 'binary:logistic', 'eval_metric': 'logloss'}
        else:
            xgb_kwargs = {'objective': 'multi:softprob',  'eval_metric': 'mlogloss'}

        xgb = self._tune(
            XGBClassifier(random_state=self.random_state, n_jobs=-1,
                          verbosity=0, **xgb_kwargs),
            {'n_estimators': [100, 200], 'max_depth': [3, 5, 7],
             'learning_rate': [0.01, 0.1]},
            X_train_scaled, y_train, cv, "XGBoost"
        )

        # ── Soft-vote ensemble ────────────────────────────────────────────────
        print("\n  Building Voting Ensemble…")
        ensemble = VotingClassifier(
            estimators=[('lr', lr), ('rf', rf), ('xgb', xgb)],
            voting='soft'
        )
        ensemble.fit(X_train_scaled, y_train)

        models = {
            'logistic_regression': lr,
            'random_forest':       rf,
            'xgboost':             xgb,
            'voting_ensemble':     ensemble,
        }
        self.models[task] = models
        return models


# =============================================================================
# SECTION 4: FEATURE IMPORTANCE
# =============================================================================

class FeatureImportanceAnalyzer:

    def __init__(self, bdi_cols, fcri_cols, feature_names):
        self.bdi_cols    = bdi_cols
        self.fcri_cols   = fcri_cols
        self.feat_names  = feature_names

    def extract(self, rf_model, xgb_model):
        rf_imp  = rf_model.feature_importances_
        xgb_imp = xgb_model.feature_importances_
        rf_norm  = rf_imp  / rf_imp.sum()
        xgb_norm = xgb_imp / xgb_imp.sum()
        df = pd.DataFrame({
            'feature':          self.feat_names,
            'rf_importance':    rf_norm,
            'xgb_importance':   xgb_norm,
            'combined':         (rf_norm + xgb_norm) / 2,
        }).sort_values('combined', ascending=False).reset_index(drop=True)
        return df

    def report_top(self, imp_df, top_n=5):
        print("\n" + "=" * 60)
        print("MOBILE APP OPTIMISATION — TOP PREDICTIVE ITEMS")
        print("=" * 60)
        top_bdi  = imp_df[imp_df['feature'].isin(self.bdi_cols)].head(top_n)
        top_fcri = imp_df[imp_df['feature'].isin(self.fcri_cols)].head(top_n)
        print(f"\nTop {top_n} BDI items:")
        for _, r in top_bdi.iterrows():
            print(f"  {r['feature']:8s}  {r['combined']:.4f}")
        print(f"\nTop {top_n} FCRI items:")
        for _, r in top_fcri.iterrows():
            feat = (r['feature'][:60] + '…') if len(r['feature']) > 60 else r['feature']
            print(f"  {feat:62s}  {r['combined']:.4f}")
        print("=" * 60)
        return {'top_bdi': top_bdi['feature'].tolist(),
                'top_fcri': top_fcri['feature'].tolist()}


# =============================================================================
# SECTION 5: EVALUATION, EXPORT & DEPLOYMENT
# =============================================================================

class ModelEvaluator:

    def __init__(self, output_dir='models'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def evaluate(self, models, X_test_scaled, y_test, task='binary', class_names=None):
        """Accuracy / Precision / Recall / F1 / ROC-AUC for every model."""
        print(f"\n{'='*60}")
        print(f"{task.upper()} EVALUATION")
        print("=" * 60)
        results = {}

        for name, model in models.items():
            y_pred = model.predict(X_test_scaled)
            res = {
                'accuracy' : accuracy_score(y_test, y_pred),
                'precision': precision_score(y_test, y_pred, average='weighted', zero_division=0),
                'recall'   : recall_score(y_test, y_pred, average='weighted', zero_division=0),
                'f1'       : f1_score(y_test, y_pred, average='weighted', zero_division=0),
            }

            # ROC-AUC (binary: standard; multiclass: macro OvR)
            if hasattr(model, 'predict_proba'):
                try:
                    y_proba = model.predict_proba(X_test_scaled)
                    if task == 'binary':
                        res['roc_auc'] = roc_auc_score(y_test, y_proba[:, 1])
                    else:
                        res['roc_auc'] = roc_auc_score(
                            y_test, y_proba, multi_class='ovr', average='macro')
                except Exception:
                    res['roc_auc'] = None
            else:
                res['roc_auc'] = None

            results[name] = res
            print(f"\n  {name.upper()}")
            print(f"  Accuracy  {res['accuracy']:.4f}  Precision {res['precision']:.4f}  "
                  f"Recall {res['recall']:.4f}  F1 {res['f1']:.4f}")
            if res['roc_auc'] is not None:
                print(f"  ROC-AUC   {res['roc_auc']:.4f}")
            if class_names:
                print(classification_report(y_test, y_pred,
                                            target_names=class_names, zero_division=0))

        return results

    def plot_confusion(self, models, X_test_scaled, y_test, task, class_names=None):
        n = len(models)
        fig, axes = plt.subplots(1, n, figsize=(5 * n, 4))
        if n == 1:
            axes = [axes]
        for ax, (name, model) in zip(axes, models.items()):
            y_pred = model.predict(X_test_scaled)
            ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred),
                                   display_labels=class_names).plot(
                ax=ax, cmap='Blues', colorbar=False)
            ax.set_title(name)
        plt.tight_layout()
        path = os.path.join(self.output_dir, f'{task}_confusion.png')
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"  Confusion matrix → {path}")

    def export(self, models, scaler, preprocessor, feature_cols,
               X_train, task='binary'):
        """Save models, scaler, label encoders, and feature metadata."""
        for name, model in models.items():
            p = os.path.join(self.output_dir, f'{task}_{name}_model.joblib')
            joblib.dump(model, p)

        joblib.dump(scaler,
                    os.path.join(self.output_dir, f'{task}_scaler.joblib'))
        joblib.dump(preprocessor.label_encoders,
                    os.path.join(self.output_dir, 'label_encoders.joblib'))

        # ── Feature metadata (CRITICAL for predict_depression.py) ────────────
        feature_means = {
            col: float(X_train[col].mean()) if col in X_train.columns else 0.0
            for col in feature_cols
        }
        meta = {'feature_cols': feature_cols, 'feature_means': feature_means}
        with open(os.path.join(self.output_dir, 'feature_metadata.json'), 'w') as f:
            json.dump(meta, f, indent=2)

        print(f"  Models, scaler, encoders and feature_metadata.json → {self.output_dir}/")


# =============================================================================
# MAIN
# =============================================================================

def main():
    print("\n" + "=" * 70)
    print("HYBRID ML FRAMEWORK FOR DEPRESSION DETECTION IN CANCER PATIENTS v2")
    print("=" * 70)

    # Ensure the output directory exists before any artifacts are saved.
    os.makedirs('models', exist_ok=True)

    data_path = os.path.join('Data', 'cancer_psychology.csv')

    print(f"\nLoading: {data_path}")
    df = pd.read_csv(data_path)
    print(f"Dataset : {df.shape[0]:,} rows × {df.shape[1]} columns")

    # 1. Preprocessing
    # Data treansormations
    preprocessor = ClinicalDataPreprocessor()
    df_proc, enc_features = preprocessor.fit_transform(df)

    # 2. Targets /labels
    # predactable values
    tve    = TargetVariableEngineer(preprocessor.bdi_columns)
    df_fin = tve.create_targets(df_proc)

    # 3. Feature matrix
    # List comphrisions
    feature_cols = [c for c in
                    preprocessor.bdi_columns + preprocessor.fcri_columns + enc_features
                    if c in df_fin.columns]
    X = df_fin[feature_cols].fillna(0)
    y_bin   = df_fin['has_depression']
    y_multi = df_fin['depression_severity_encoded']

    print(f"\nFeature matrix : {X.shape}")

    # 4. Single stratified split — shared by both binary and multiclass tasks
    #    (FIXED: v1 made two independent splits and the scaler was overwritten)
    X_train, X_test, y_bin_tr, y_bin_te = train_test_split(
        X, y_bin, test_size=0.2, random_state=RANDOM_STATE, stratify=y_bin)
    y_multi_tr = y_multi.loc[X_train.index]
    y_multi_te = y_multi.loc[X_test.index]

    # 5. Scaler — fit ONCE on training data, reuse for both tasks
    scaler         = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)

    print(f"Train : {X_train.shape[0]:,}   Test : {X_test.shape[0]:,}")

    # 6. Training
    pipeline = DepressionClassificationPipeline(random_state=RANDOM_STATE)
    bin_models   = pipeline.train(X_train_scaled, y_bin_tr,   task='binary')
    multi_models = pipeline.train(X_train_scaled, y_multi_tr, task='multiclass')

    # 7. Feature importance
    analyzer   = FeatureImportanceAnalyzer(preprocessor.bdi_columns,
                                           preprocessor.fcri_columns,
                                           feature_cols)
    imp_df     = analyzer.extract(bin_models['random_forest'], bin_models['xgboost'])
    top_items  = analyzer.report_top(imp_df, top_n=5)
    imp_df.to_csv(os.path.join('models', 'feature_importance.csv'), index=False)

    # 8. Evaluation
    evaluator = ModelEvaluator(output_dir='models')

    bin_names    = ['No Depression', 'Has Depression']
    bin_results  = evaluator.evaluate(bin_models,   X_test_scaled, y_bin_te,   'binary',     bin_names)
    evaluator.plot_confusion(bin_models,   X_test_scaled, y_bin_te,   'binary',     bin_names)

    present_cls  = sorted(y_multi_te.unique())
    multi_names  = [tve.SEVERITY_LABELS[i] for i in present_cls]
    multi_results= evaluator.evaluate(multi_models, X_test_scaled, y_multi_te, 'multiclass', multi_names)
    evaluator.plot_confusion(multi_models, X_test_scaled, y_multi_te, 'multiclass', multi_names)

    # 9. Export (binary scaler saved; same scaler used for multiclass)
    evaluator.export(bin_models,   scaler, preprocessor, feature_cols, X_train, task='binary')
    evaluator.export(multi_models, scaler, preprocessor, feature_cols, X_train, task='multiclass')

    # 10. Summary
    best_bin   = max(bin_results,   key=lambda x: bin_results[x]['f1'])
    best_multi = max(multi_results, key=lambda x: multi_results[x]['f1'])
    print("\n" + "=" * 70)
    print("COMPLETE")
    print("=" * 70)
    print(f"Best binary model     : {best_bin}  (F1={bin_results[best_bin]['f1']:.4f})")
    print(f"Best multiclass model : {best_multi}  (F1={multi_results[best_multi]['f1']:.4f})")
    print(f"Top BDI  items (mobile): {top_items['top_bdi']}")
    print(f"Top FCRI items (mobile): {top_items['top_fcri']}")
    print(f"Artifacts saved to    : models/")
    print("=" * 70)

    return {
        'binary_models':   bin_models,
        'multi_models':    multi_models,
        'feature_cols':    feature_cols,
        'feature_imp':     imp_df,
        'top_items':       top_items,
        'preprocessor':    preprocessor,
        'target_engineer': tve,
        'scaler':          scaler,
    }


if __name__ == '__main__':
    results = main()